### ISSUE TITLE
清理id迁移遗留的旧数据

### ISSUE THREAD

**Issue by Gizeta** [Gizeta/kcdata#222]
田中有改id的陋习，因为更新脚本没有清理旧id的机制，遗留了很多目前没有在使用的条目，需要摸排下情况统一清理掉。

目前已知：
- [ ] id>500 && id<1000的深海装备

**需要确认清理后是否影响wiki数据**

**Comment by Mhmdalimhmd** [comment]
> Stacktrace:
> 
> ```
> Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f080058
>   at android.content.res.Resources.getValue(Resources.java:1118)
>   at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:330)
>   at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
>   at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
>   at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:755)
>   at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
>   at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:88)
>   at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:128)
>   at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:149)
>   at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:29)
>   at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:54)
>   at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:202)
>   at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:183)
>   at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:520)
>   at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
>   at com.huetoyou.chatexchange.ui.activity.SplashActivity.onCreate(SplashActivity.java:18)
>   at android.app.Activity.performCreate(Activity.java:5133)
>   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
>   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
> ```
